include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - linux/**
    - macos/**
    - windows/**

linter:
  rules:
    unnecessary_underscores: false
